description = "Generates a new release in GitHub."

prompt = """
Execute the release process for version

## Release Process
To release a new version, follow these steps:
1.  Update Changelog with a summary of the all changes that have been made to the repo since tag vX.Y.(Z-1)
2.  Update version from `x.y.z-SNAPSHOT` to `x.y.z` in `package.json`.
3.  Commit changes to Git with the same summary commit message as was placed in the change log.
4.  Create and push tag `x.y.z` to GitHub. Ensure the tag message includes the relevant changelog entries and the standard release description.
5.  Update version from `x.y.z` to `x.y.(z+1)-SNAPSHOT` in `package.json`.
6.  Commit version update and push to GitHub (e.g., `chore(release): begin vX.Y.(Z+1) development`).
"""