name: Build Mobile Apps (Android & iOS)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

permissions:
  contents: write
  packages: write

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install dependencies
      run: npm ci

    - name: Build Svelte app
      run: npm run build

    - name: Setup Capacitor Android
      run: |
        # Remove existing Android platform if it exists
        if [ -d "android" ]; then
          rm -rf android
        fi
        npx cap add android
        npx cap sync android

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: tai-chi-app-android-${{ github.ref_name || github.event.inputs.version }}
        path: android/app/build/outputs/apk/debug/app-debug.apk



  create-release:
    runs-on: ubuntu-latest
    needs: [build-android]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get commit message for tag
      id: get_commit_message
      run: echo "commit_message=$(git log -1 --pretty=%B ${{ github.ref_name }})" >> $GITHUB_OUTPUT

    - name: Download Android APK artifact
      uses: actions/download-artifact@v4
      with:
        name: tai-chi-app-android-${{ github.ref_name || github.event.inputs.version }}
        path: artifacts/android



    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/android/*.apk
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: ${{ steps.get_commit_message.outputs.commit_message }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}