name: Build Mobile Apps (Android & iOS)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

permissions:
  contents: write
  packages: write

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install dependencies
      run: npm ci

    - name: Build Svelte app
      run: npm run build

    - name: Setup Capacitor Android
      run: |
        # Remove existing Android platform if it exists
        if [ -d "android" ]; then
          rm -rf android
        fi
        npx cap add android
        npx cap sync android

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: tai-chi-app-android-${{ github.ref_name || github.event.inputs.version }}
        path: android/app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    runs-on: macos-latest
    needs: build-android # Ensure Android build completes first if desired, or remove if independent

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install dependencies
      run: npm ci

    - name: Build Svelte app
      run: npm run build

    - name: Setup Capacitor iOS
      run: |
        # Remove existing iOS platform if it exists
        if [ -d "ios" ]; then
          rm -rf ios
        fi
        npx cap add ios
        npx cap sync ios

    - name: Install CocoaPods
      run: |
        gem install cocoapods

    - name: Build iOS App
      run: |
        cd ios
        pod install --repo-update
        xcodebuild -workspace App/App.xcworkspace -scheme App -configuration Release -destination 'generic/platform=iOS' archive -archivePath build/App.xcarchive
        # NOTE: For a successful release build, you will need to configure code signing.
        # This typically involves:
        # 1. Storing Apple Developer certificates and provisioning profiles securely (e.g., in GitHub Secrets).
        # 2. Using a tool like Fastlane Match or directly configuring xcodebuild with signing identities.
        # Example for exporting IPA (requires signing identities):
        # xcodebuild -exportArchive -archivePath build/App.xcarchive -exportPath build -exportOptionsPlist exportOptions.plist
        # For now, this step will only archive. Exporting IPA requires proper signing setup.

    - name: Upload iOS Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: tai-chi-app-ios-${{ github.ref_name || github.event.inputs.version }}
        path: ios/build/App.xcarchive # Upload the archive for now, IPA export needs signing

  create-release:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios] # This job depends on both Android and iOS builds
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get commit message for tag
      id: get_commit_message
      run: echo "commit_message=$(git log -1 --pretty=%B ${{ github.ref_name }})" >> $GITHUB_OUTPUT

    - name: Download Android APK artifact
      uses: actions/download-artifact@v4
      with:
        name: tai-chi-app-android-${{ github.ref_name || github.event.inputs.version }}
        path: artifacts/android

    - name: Download iOS Archive artifact
      uses: actions/download-artifact@v4
      with:
        name: tai-chi-app-ios-${{ github.ref_name || github.event.inputs.version }}
        path: artifacts/ios

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/android/*.apk
          artifacts/ios/*.xcarchive # Upload the archive for now
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: ${{ steps.get_commit_message.outputs.commit_message }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}